Chromosom : 
  - "1"
  - "2"
  - "3"
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"
  - "13"
  - "14"
  - "15"
  - "16"
  - "17"
  - "18"
  - "19"
  - "20"
  - "21"
  - "22"
  - "MT"
  - "X"
  - "Y"

NCBI_id :
  - "SRR628589"
  - "SRR628588"
  - "SRR628587"
  - "SRR628586"
  - "SRR628585"
  - "SRR628584"
  - "SRR628583"
  - "SRR628582"
  
Individual_conditions :
  SRR628586 : WT
# SRR636533 : WT
# SRR636531 : WT
# SRR636532 : WT
# SRR628589 : WT
# SRR628588 : WT
# SRR628587 : WT
# SRR628586 : WT
# SRR628585 : WT
# SRR628584 : WT
# SRR628583 : WT
# SRR628582 : WT

#  SRR628582 : SF3B1 
#  SRR628583 : SF3B1
#  SRR628584 : SF3B1
#  SRR628585 : WT
#  SRR628586 : WT
#  SRR628587 : WT
#  SRR628588 : WT
#  SRR628589 : WT

GetFastq :
  Repertory : fastq-dump/
  container : images/fastq-dump

GetGenome :
  Repertory : Genome/
  container : images/fastq-dump

GetAnnot :
  Repertory : GenomeAnnot/
  Extension : .gtf
  Filename : genome_annot
  container : images/fastq-dump
  genome_ref : GRCh38

IndexGenome:
  Repertory : IndexGenome/
  container : images/star

MappingSTAR :
  Repertory : MappingSTAR/
  container : images/star

CountReads :
  Repertory : CountReads/
  Extension : .counts
  Filename :  CountReads
  container : images/subread
